# Generated by Django 5.1.7 on 2025-04-20 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='floor',
            field=models.CharField(choices=[('all', 'All'), ('ground', 'Ground'), ('floor 1', 'Floor 1'), ('floor 2', 'Floor 2'), ('floor 3', 'Floor 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manager',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RentPaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('payment_id', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='INR', max_length=4)),
                ('payment_status', models.CharField(default='Pending', max_length=40)),
                ('amount_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(default='UPI', max_length=100)),
                ('order_receipt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.IntegerField(default=1)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='hub.allocatedshop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.allocatedshop')),
            ],
        ),
    ]
